ft-booking accommodation #175743342
atlp-rwanda/space-bn-backend pull request #15
Opened 2020-12-17 14:02 UTC by jemmyarina

#### What does this PR do?
**ALLOW ANY USER TO REQUEST AN ACCOMMODATION** 

#### Description of Task to be completed?
**ANY USER CAN POST A REQUEST,  UPDATE AND DELETE A REQUEST BY ID, GET ALL REQUESTS**

#### How should this be manually tested?
**RUN THE API APP** 

#### Any background context you want to provide?
**N/A**

#### What are the relevant pivotal tracker stories?
**N/A**

#### Screenshots (if appropriate)
**N/A**

2020-12-18 12:28 UTC, Anguandia commented
Did you rebase? check the failing checks and rectify, please

2020-12-19 20:49 UTC, furebo approved these changes

2021-01-05 08:08 UTC, leny62 approved these changes

2021-01-05 08:10 UTC, leny62 requested changes
Kindly rebase your PR!

2021-01-05 15:28 UTC, Anguandia commented
Please rebase @jemmyarina

2021-01-06 20:27 UTC, leny62 approved these changes

2021-01-13 18:30 UTC, closed without merging