[finishes #175743307] configuring unit tests
atlp-rwanda/space-bn-backend pull request #2
Opened 2020-11-20 17:12 UTC by leny62

##Description
Configuration of unit tests

##Description of Task to be completed?
This branch contains files that configures unit testing using Mocha as the test runner with also chai and chai-http for the unit tests.

##How should this be manually tested?
*Clone this repo
*Open the terminal or git bash
*write npm i 
and lastly 
*write npm test/ npm run test

##What are the relevant pivotal tracker stories?
Setup unit testing [test](https://www.pivotaltracker.com/story/show/175743307) #175743307

2020-11-23 15:08 UTC, Anguandia requested changes
First.js and add.js are not really necessary, please test the index route instead

2020-11-23 15:08 UTC, Anguandia commented on src/tests/simple.test.js
> +} )
You have not tested any HTTP request though

2020-11-23 15:08 UTC, Anguandia commented on src/app.js
> +});
You need to test this route

2020-11-23 15:08 UTC, Anguandia commented on src/tests/simple.test.js
> +import first from '../controllers/first';
What happened to the test client?
Please create and export a general setting for tests that will be imported in all subsequent test files

2020-11-23 15:08 UTC, Anguandia commented on test.js
> +var foo = bar;
??? is this relevant?

2020-11-23 15:09 UTC, Anguandia commented on test.js
> +var foo = bar;
Also squash the commits

2020-11-24 11:18 UTC, leny62 commented on src/app.js
> +});
Noted!

2020-11-24 11:25 UTC, leny62 commented on test.js
> +var foo = bar;
This was a simple file to test Eslint

2020-11-25 16:40 UTC, closed without merging