Ch postgres
atlp-rwanda/space-bn-backend pull request #3
Opened 2020-11-21 13:56 UTC by jemmyarina

What does this PR do?
This PR add a PR request for merging with DEVELOP branch 

Description of Task to be completed?
POSTGRES CONFIGURATION AND SEQUELIZE SETUP

How should this be manually tested?
IT SHOULD BE TESTED MANUALLY USING PGADMIN 4

Any background context you want to provide?
N/A

What are the relevant pivotal tracker stories?
#175743303

What are the relevant Github Issues?
N/A

Screenshots (if appropriate)
N/A

Questions:
N/A

2020-11-23 08:43 UTC, Anguandia requested changes
Please work on the following:
- PR description
- Add node modules to git ignore
- Rebase and resolve conflicts

2020-11-23 08:46 UTC, Anguandia requested changes
Add node_modules to git ignore
Improve the PR description
Rebase and resolve conflicts
Always squash multiple commits

2020-11-25 12:46 UTC, leny62 requested changes
The package-lock.json is presenting many conflicts. So you may delete it, rebase and reinitialise/reinstall your npm.

2020-11-25 13:18 UTC, furebo reviewed
The PR description  is about the configuration of postgres and set up of sequelize

2020-11-26 07:37 UTC, leny62 approved these changes
Good Job @jemmyarina , Let's now see whether this PR isn't conflicting with the base branch.

2020-11-26 08:32 UTC, furebo approved these changes
Thank you for solving conflicts issue

2020-11-26 15:49 UTC, Anguandia requested changes

2020-11-26 15:49 UTC, Anguandia commented on .babelrc
> +<<<<<<< HEAD
You didn't finish with the process of rebasing/resolving conflicts, please complete this process

2020-11-26 15:49 UTC, Anguandia commented on .babelrc
> +=======
Same here

2020-11-26 15:49 UTC, Anguandia commented on .babelrc
> +>>>>>>> index and config
and here

2020-11-26 15:49 UTC, Anguandia commented on .hound.yml
> +>>>>>>> adding seeds successfully
Complete the rebasing please

2020-11-30 23:50 UTC, Monehin reviewed
Fix the Deepcode Issue

Just follow the example from the [JsDocs](https://jsdoc.app/tags-param.html#:~:text=The%20%40param%20tag%20provides%20the,a%20description%20of%20the%20parameter) Documentation to define the model's params

2020-12-01 05:18 UTC, Anguandia approved these changes

2020-12-01 05:18 UTC, merged