#175743327 ft(manager): Avail requests to manager for approval
atlp-rwanda/space-bn-backend pull request #39
Opened 2021-01-24 12:58 UTC by SamuelSabasNayo

#### What does this PR do?
- Avail requests to a manager for approval or rejection.

#### Description of Task to be completed? 
- Allows a manager to get, add, and update requests.
- Implement API documentation by using Swagger.
- Test all APIs by using mocha/chai.

#### How should this be manually tested?
- Clone the repository.

- In your home directory move into the cloned folder by cd this branch **`ft-manager-#175743327`**.

- Then run **`npm install`** to install all dependencies.

- Run **`npm migrate`** to create tables.

- Run **`npm seed`** to insert some dummy data.

- Run **`npm start`** to start the server.

- In your default browser navigate to **`http://http://localhost:5000/api-docs`** to assess the endpoints regarding to manager.

- Run **`npm test`** to test the codes.

#### Any background context you want to provide?
- To successfully get, add, and update requests as a manager, do the following:
	- Signup as a new user **`manager@bn.com`**.
	- Sign in as a Super Admin **`spacenomad@gmail.com`**.
	- Assign a role to the registered user (`manager@bn.com`) to become **`MANAGER`**.

	- Sign in as manager **`manager@bn.com`**.
- As a manager, you can get, add, and update requests.

#### What are the relevant Pivotal Tracker stories?
- [#175743327](https://www.pivotaltracker.com/story/show/175743327)

#### Screenshots (if appropriate)
- 
<img width="1440" alt="Screen Shot 2021-01-24 at 14 52 23" src="https://user-images.githubusercontent.com/60556879/105630868-1eaf4980-5e54-11eb-8f0b-fbe6d90e3161.png">

#### Questions:
- N/A

2021-01-25 10:40 UTC, SimonImanigirimpuhwe requested changes

2021-01-25 10:40 UTC, SimonImanigirimpuhwe commented on src/controllers/managerController.js
> +  }
I can see here you can create one request a million times with unique data....  and add `idUser` manually!

2021-01-25 10:40 UTC, SimonImanigirimpuhwe commented on src/tests/manager.test.js
> +                  console.log(res.body);
remove this console.log

2021-01-25 10:54 UTC, ConstantineMaliza approved these changes
Great work @SamuelSabasNayo work those change @SimonImanigirimpuhwe  said other tests work well

2021-01-25 11:20 UTC, SamuelSabasNayo commented on src/controllers/managerController.js
> +  }
Yeah, sure!

2021-01-26 12:52 UTC, kabano89 approved these changes

2021-01-26 13:06 UTC, SimonImanigirimpuhwe approved these changes
Good implementation

2021-01-26 15:20 UTC, merged