comment thread#175743328
atlp-rwanda/space-bn-backend pull request #40
Opened 2021-01-25 15:56 UTC by ConstantineMaliza

#### What does this PR do?
- Comment thread

#### Description of Task to be completed?
- User is able to post a comment to a travel request to give additional information
- User is able to see the posted comment within the thread
#### Write tests for roles endpoints
#### How should this be manually tested?

- Clone the repository
- In your home directory cd this branch ft comments
- Then run npm install to install all dependencies
- Run npm start to start the server
- In you postman go to http://localhost:5000/request/requestId/comment to write a comment  
- To read comment use endpoint `GET` http://localhost:5000/requestId comments
- `All endpoint you get after sign in or sign out`

**As Manager can reply comment left by requester** 

- Login in as Manager
- Go to the endpoint `post` with path `http://localhost:5000/request/requestId/comment/commentId/reply`
- Body replyContent: ""
- To get all comment  as a manager go to the endpoint `get` with path`http://localhost:5000/comments/`

#### Any background context you want to provide?
N/A
What are the relevant Pivotal Tracker stories?
#175743328
Screenshots (if appropriate)
N/A
Questions:
N/A

2021-01-27 17:40 UTC, SamuelSabasNayo commented
Can you label this PR as **WIP**, since it is not yet **ready**?

2021-01-31 07:21 UTC, PatrickNiyogitare28 approved these changes
Yeah! it is ok.

2021-01-31 08:45 UTC, SamuelSabasNayo requested changes

2021-01-31 08:45 UTC, SamuelSabasNayo commented on .env.example
> +<<<<<<< HEAD
Can you remove this HEAD?

2021-01-31 08:45 UTC, SamuelSabasNayo commented on locales/en.json
> +}
Just to remind you that total lines are 63.

2021-01-31 08:45 UTC, SamuelSabasNayo commented on src/database/seeders/20201223133014-User.js
> +      roleId: 2,
Initially roleId= 5.

2021-01-31 08:45 UTC, SamuelSabasNayo commented on src/database/seeders/20210120052931-userRoles.js
> +      {
No need for seeding the MANAGER role, since we created him in database/managerRole.js.

2021-01-31 08:45 UTC, SamuelSabasNayo commented on src/tests/comment.test.js
> +    const user = await model.User.create({
You repeated creating a user many times, can you do that once and reuse her token?

2021-01-31 16:58 UTC, SamuelSabasNayo approved these changes
Good work @Maliza.

2021-01-31 18:24 UTC, merged