(social-media-login) has been implemented
atlp-rwanda/space-bn-backend pull request #41
Opened 2021-01-25 21:42 UTC by Imaraika

- What does this PR do?
   - login via Google and Facebook

- Description of Task to be completed?

  - Setting up passport google Authentication configuration.
  - As a user I should be able to login via Google and Facebook
- How should this be manually tested?
  - Clone the repository.
  - In your home directory move into the cloned folder by cd space-bn-backend
  - Then run npm install to install all dependencies.
  - Run npm start to start the server.
- Any background context you want to provide?
  - N/A

- What are the relevant Pivotal Tracker stories?
   #175743317

- Screenshots (if appropriate)
   N/A
- Questions
  N/A

2021-01-26 20:09 UTC, Anguandia commented
Please provide your environment variables on travis and write tests for your feature @Imaraika

2021-01-27 04:09 UTC, Anguandia commented
Why do you have 2 different PRs for the same feature? Please delete the unnecessary extra

2021-01-31 08:05 UTC, Anguandia requested changes
Please incorporate tests

2021-02-04 18:42 UTC, Imaraika commented
> Please incorporate tests
yes yes please ! I have worked on the tests! now all tests are passing

2021-02-04 18:45 UTC, Imaraika commented
> Please incorporate tests
yes yes please ! I have worked on the tests! now all tests are passing

2021-02-04 18:52 UTC, Imaraika commented
> Please provide your environment variables on travis and write tests for your feature @Imaraika

I have done this also ! thanks

2021-02-08 12:38 UTC, SamuelSabasNayo commented
@Imaraika you can increase your test coverage, since your coverage of 94% is below the existing one, and it is required.

2021-02-10 16:14 UTC, ConstantineMaliza requested changes
great work @Imaraika  cover all test because it affects the test coverage on develop if it is not covered

2021-02-10 16:17 UTC, SimonImanigirimpuhwe reviewed
Solve some conflicting files and then we are ready to go

2021-02-11 20:29 UTC, SamuelSabasNayo requested changes

2021-02-11 20:29 UTC, SamuelSabasNayo commented on locales/en.json
> +	"Request does not exist!": "Request does not exist!"
Put a comma at the end of this line.

2021-02-11 20:29 UTC, SamuelSabasNayo commented on src/routes/googleOuth.route.js
> +      id: req.user.id,
You should use destructuring rather than repeating **req.user**.

2021-02-11 20:29 UTC, SamuelSabasNayo commented
Please rebase.

2021-02-11 20:54 UTC, closed without merging