Ft facility reactions #175743343
atlp-rwanda/space-bn-backend pull request #43
Opened 2021-01-29 10:04 UTC by SimonImanigirimpuhwe

2021-01-29 21:11 UTC, Anguandia requested changes
Please rebase and secure peer reviews. Circle CI setup has been merged

2021-01-30 07:27 UTC, PatrickNiyogitare28 approved these changes

2021-01-30 10:40 UTC, SamuelSabasNayo requested changes
Please, rebase to develop in order to have an updated package.json (with **nodemailer**).

2021-01-30 10:42 UTC, SimonImanigirimpuhwe commented
> Please, rebase to develop in order to have an updated package.json (with **nodemailer**).

How comes I have to rebase since I don't have any conflicts.....

2021-01-30 11:09 UTC, SamuelSabasNayo approved these changes

2021-01-30 11:11 UTC, Anguandia approved these changes

2021-01-30 11:13 UTC, merged