#176655416 Fix user model and revise manager privileges
atlp-rwanda/space-bn-backend pull request #45
Opened 2021-01-29 12:28 UTC by SamuelSabasNayo

#### What does this PR do?
- Fix User model definition and revise Manager privileges.

#### Description of Task to be completed? 
- Replace user profession with his manager Id.
- Allows Super Admin & Manager to assign manager Id to a user.
- Allows a manager to get, add, and update requests of the users who belong to him/her.
- Implement API documentation by using Swagger.
- Test all APIs by using mocha/chai.

#### How should this be manually tested?
- Clone the repository.

- In your home directory move into the cloned folder by cd this branch **`bug-fix-manager-#176655416`**.

- Then run **`npm install`** to install all dependencies.

- Run **`npm migrate`** to create tables.

- Run **`npm seed`** to insert some dummy data.

- Run **`npm start`** to start the server.

- In your default browser navigate to **`http://http://localhost:5000/api-docs`** to assess the endpoints regarding to manager.

- Run **`npm test`** to test the codes.

#### Any background context you want to provide?
- To successfully get, add, and update requests as a manager, do the following:
	- Sign in as backend manager with the following credential Email: **`backendmanager@bn.com`**, password: **`B${hashedPswd}`**.
	- Signup a new user.
	- Assign a user with a managerId.
	- User can create a request.
- As a manager, you can get, add, and update requests of requesters who belong to him/her.

#### What are the relevant Pivotal Tracker stories?
- [#176655416](https://www.pivotaltracker.com/story/show/175743334)

#### Screenshots (if appropriate)
- <img width="1440" alt="Screen Shot 2021-01-28 at 20 06 19" src="https://user-images.githubusercontent.com/60556879/106275256-31ec5b80-623e-11eb-8ac0-b20cedd1fdf1.png">

#### Questions:
- N/A

2021-01-29 21:17 UTC, Anguandia commented
Please remedy the failing check on CircleCI

2021-01-30 07:29 UTC, PatrickNiyogitare28 requested changes
Rebase to have checks passing! now circle-ci config feature is merged

2021-01-30 09:40 UTC, PatrickNiyogitare28 approved these changes

2021-01-30 12:53 UTC, SimonImanigirimpuhwe approved these changes

2021-01-30 12:56 UTC, ConstantineMaliza approved these changes

2021-01-30 12:57 UTC, ConstantineMaliza approved these changes

2021-01-30 13:58 UTC, merged