Add search functionality request#175743332
atlp-rwanda/space-bn-backend pull request #53
Opened 2021-02-07 17:57 UTC by ConstantineMaliza

#### What does this PR do?

- Manager and Requester can search request

#### Description of Task to be completed? 

- To search requester must be the authenticated user or manager

#### How should this be manually tested?

- Clone the repo 

- In your home directory  cd this branch **`Search-API#175743332`**

- Then run **`npm install`** to install all dependencies

- Run **`npm start`** to start the server

- In your default browser navigate to **`http://localhost:5000`** 

#### Any background context you want to provide?

- To requester use the endpoint `get` in path **`http://localhost:5000/request/search`** 
- To manager use the endpoint `get` **`http://localhost:5000/request/search/manager`**  
- To manager  to search on requester table use the endpoint `get` **`http://localhost:5000/request/search/requester`**  
- **we will params according to the query** 

#### What are the relevant Pivotal Tracker stories?

- #175743332

#### Screenshots (if appropriate)
- N/A

#### Questions:

- N/A

2021-02-07 20:53 UTC, joshwambere requested changes

2021-02-07 20:53 UTC, joshwambere commented on src/controllers/searchController.js
> +    const Request = await model.request.findAll({
Try checking if the request to the database has gone successfully so you can know which error to throw if it didn't go through cz when you pass incorrect query like `?idUser=kl `the request keep going endlessly it should show bad request or another error message

2021-02-08 08:34 UTC, PatrickNiyogitare28 approved these changes

2021-02-08 16:14 UTC, joshwambere approved these changes

2021-02-08 17:11 UTC, SimonImanigirimpuhwe requested changes

2021-02-08 17:11 UTC, SimonImanigirimpuhwe commented on src/tests/search.test.js
> +            profession: "",
Remove this field since we don't have it in user model

2021-02-08 17:11 UTC, SimonImanigirimpuhwe commented on src/tests/search.test.js
> +            profession: "",
The same here

2021-02-08 19:43 UTC, SimonImanigirimpuhwe approved these changes

2021-02-08 20:06 UTC, SamuelSabasNayo requested changes

2021-02-08 20:06 UTC, SamuelSabasNayo commented on src/controllers/searchController.js
> +      if (key === 'requestStatus') queries.push({ [key]: { [Op.iLike]: `%${value}%` } }) ;
Please try to query or search a request using all possible string fields (i.e. requesterName, hotelName, location, roomType)

2021-02-09 12:11 UTC, SamuelSabasNayo approved these changes

2021-02-09 13:32 UTC, merged