#176841113 ft(question): Any user can add a question & read FAQ
atlp-rwanda/space-bn-backend pull request #55
Opened 2021-02-08 14:17 UTC by SamuelSabasNayo

#### What does this PR do?
- Allows any user to add a question and read FAQ.

#### Description of Task to be completed? 
- Allows any user to add a question and read FAQ.
- Implement API documentation by using Swagger.
- Test all APIs by using mocha/chai.

#### How should this be manually tested?
- Clone the repository.

- In your home directory move into the cloned folder by cd this branch **`ft-questions-#176841113`**.

- Run **`npm migrate:reset`** to create tables.

- Run **`npm seed`** to insert some dummy data.

- Run **`npm start`** to start the server.

- In your default browser navigate to **`http://localhost:5000/api-docs`** to assess the endpoints regarding requests.

- Run **`npm test`** to test the codes.

#### Any background context you want to provide?
- N/A

#### What are the relevant Pivotal Tracker stories?
- [#176841113](https://www.pivotaltracker.com/story/show/176841113)

#### Screenshots (if appropriate)
- 
<img width="1440" alt="Screen Shot 2021-02-08 at 16 13 55" src="https://user-images.githubusercontent.com/60556879/107231439-fcf3bc00-6a28-11eb-920f-e40ddd4124c3.png">

#### Questions:
- N/A

2021-02-10 12:54 UTC, PatrickNiyogitare28 approved these changes

2021-02-10 14:38 UTC, SimonImanigirimpuhwe requested changes

2021-02-10 14:38 UTC, SimonImanigirimpuhwe commented on src/controllers/questionController.js
> +  }
What if no question with the specified id found? It automatically end up in catch block, you should first check the existence of question with that id.

2021-02-10 14:38 UTC, SimonImanigirimpuhwe commented on src/controllers/questionController.js
> +      return res.status(500).json({ error: error.message });
Consider returning a user friendly message like internal server error

2021-02-10 14:39 UTC, SimonImanigirimpuhwe commented on src/controllers/questionController.js
> +  }
We also need endpoint of deleting questions, because the case may happen that questions need to be deleted.

2021-02-10 16:17 UTC, ConstantineMaliza approved these changes

2021-02-11 06:39 UTC, SimonImanigirimpuhwe approved these changes

2021-02-11 19:00 UTC, Anguandia approved these changes

2021-02-11 19:01 UTC, merged