#175743347 ft(destinations): add most travelled destinations
atlp-rwanda/space-bn-backend pull request #60
Opened 2021-02-14 12:34 UTC by SimonImanigirimpuhwe

#### What does this PR do?

- Implement most travelled destinations

#### Description of Task to be completed? 

- Get all requests with approved status
- Filter locations of those requests
- Display found request from the highest frequency

#### How should this be manually tested?

- Clone the repo 

- In your home directory  cd this branch **`ft-actioned-request-notification-#175743330`**

- Then run **`npm install`** to install all dependencies

- Run **`npm start`** to start the server

- Using postman  hit this endpoint **`http://localhost:5000/requests/destinations`** 
- Use postman try to randomly pick `id` of any user assigned to you and then try to action on his/her request, you should see in the browser a notification.

#### Any background context you want to provide?

- To be able to see most travelled destinations you need first to login 

#### What are the relevant Pivotal Tracker stories?

- [#175743347](https://www.pivotaltracker.com/n/projects/2476678/stories/175743347)

#### Screenshots (if appropriate)

<img width="1112" alt="Screen Shot 2021-02-14 at 14 29 25" src="https://user-images.githubusercontent.com/54619678/107876832-32892100-6ed1-11eb-8de9-9957b2c29d89.png">

#### Questions:

- N/A

2021-02-15 11:33 UTC, ConstantineMaliza approved these changes

2021-02-17 20:20 UTC, SamuelSabasNayo requested changes
Good work!

2021-02-17 20:20 UTC, SamuelSabasNayo commented on src/controllers/requestController.js
> +      if (!allRequests || allRequests.count === 0) res.status(404).json({ message: res.__('No destination found!') });
You only tested the happy path, try to test this line.

2021-02-18 14:39 UTC, SamuelSabasNayo approved these changes

2021-02-20 15:45 UTC, Anguandia approved these changes

2021-02-21 14:02 UTC, merged