#177028356 bug(images-url): Fix uploading images to cloudinary
atlp-rwanda/space-bn-backend pull request #67
Opened 2021-02-21 23:32 UTC by SamuelSabasNayo

#### What does this PR do?
- Allows uploading images for user profile update, creating hotel and facility.

#### Description of Task to be completed? 
- Allows any authenticated user to upload his/her profile picture. 
- Allows any authenticated user to upload a hotel image.
- Allows any authenticated user to upload a facility image.

#### How should this be manually tested?
- Clone the repository.

- In your home directory move into the cloned folder by cd this branch **`bug-fix-images-#177028356`**.

- Then run **`npm install`** to install all dependencies.

- Run **`npm migrate`** to create tables.

- Run **`npm seed`** to insert some dummy data.

- Run **`npm start`** to start the server.

- Using Postman
    - Add image by **http://localhost:5000/user/addimage/:id**
    - Create a hotel by **http://localhost:5000/hotels**
    - Create a facility by **http://localhost:5000/facility**

#### Any background context you want to provide?
- N/A

#### What are the relevant Pivotal Tracker stories?

- [#177028356](https://www.pivotaltracker.com/story/show/177028356)

#### Screenshots (if appropriate)

- 
<img width="1440" alt="Screen Shot 2021-02-22 at 01 21 55" src="https://user-images.githubusercontent.com/60556879/108642330-37d80400-74ad-11eb-8bad-0484540a71ae.png">
<img width="1440" alt="Screen Shot 2021-02-22 at 01 23 57" src="https://user-images.githubusercontent.com/60556879/108642337-42929900-74ad-11eb-9edc-945895d1ebbc.png">

#### Questions:

- N/A

2021-02-24 16:28 UTC, PatrickNiyogitare28 requested changes
Hi! revisit tests ASAP, they are failing

2021-02-24 17:20 UTC, SamuelSabasNayo commented
> Hi! revisit tests ASAP, they are failing

Yeah sure.

2021-02-26 03:51 UTC, PatrickNiyogitare28 approved these changes

2021-02-26 16:58 UTC, SamuelSabasNayo reviewed
good work for uploading

2021-02-26 17:01 UTC, SimonImanigirimpuhwe approved these changes

2021-02-26 17:07 UTC, ConstantineMaliza approved these changes

2021-02-26 18:53 UTC, ConstantineMaliza approved these changes

2021-02-26 19:13 UTC, merged